baseURL: "https://amyth.dev" 
title: Amit Chaudhari
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: About
                  url: about
                  weight: 1
                - name: Resume
                  url: resume
                  weight: 2
                - name: Tags
                  url: tags/
                  weight: 3
                - name: Categories
                  url: categories
                  weight: 4
                - name: Archives
                  url: archives
                  weight: 5
                - name: Notes
                  url: https://notes.amyth.dev
                - name: Search
                  url: search/
                  weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Amit Chaudhari's Personal Little space on the Interwebz."
    author: Amit Chaudhari
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["homeCover.webp"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title : "Hello there 👋"
        Content: >
            I'm Amit, Software developer with an interest in Backend, InfoSec & Custom keyboards. 


            This is my little space on the internet. 


            Hope you have fun looking around. Cheers!
    # socialIcons:
    #     - name: github
    #       url: "https://github.com/amit-chaudhari1"
    #     - name: stackoverflow
    #       url: "https://stackoverflow.com/users/7249591/amit-chaudhari"
    #     - name: linkedin
    #       url: "https://www.linkedin.com/in/amyth-dev/"
    #     - name: twitter
    #       url: "https://twitter.com/amyth_dev"
    #     - name: Rss
    #       url: "index.xml"
    editPost:
        # open up a new issue template within that project
        URL: "https://github.com/amit-chaudhari1/amyth.dev/labels"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "favicon.ico"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        extensions:
            definitionList : true
            footnote : true
            linkify : true
            linkifyProtocol : 'https'
            strikethrough : true
            table : true
            taskList : true
            typographer : true
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
